#[derive(Clone, Debug)]
pub struct Project {
    pub slug: &'static str,
    pub title: &'static str,
    pub tagline: &'static str,
    pub description: &'static str,
    pub stack: Vec<&'static str>,
    pub categories: Vec<&'static str>,
    pub status: &'static str,
    pub link: Option<&'static str>,
    pub year: &'static str,
    pub highlights: Vec<&'static str>,
}

pub fn all_projects() -> Vec<Project> {
    vec![
        Project {
            slug: "bund-calculator",
            title: "Bund Wall Calculator",
            tagline: "EPA SPCC compliance engine for fuel storage containment",
            description: "A production web calculator that sizes secondary containment bunds for fuel and transformer oil storage. Implements 40 CFR 112.8(c)(2) (110% rule), displacement accounting, multi-tank scenarios, and insufficient safety factor warnings. Deployed to Hostinger and used by practicing engineers.",
            stack: vec!["JavaScript", "HTML5", "CSS", "Alpine.js"],
            categories: vec!["Engineering", "Software"],
            status: "Deployed",
            link: None,
            year: "2025",
            highlights: vec![
                "Implements EPA 40 CFR 112 containment rules",
                "Multi-tank and mixed-shape bund support",
                "Structural wall-thickness and hydrostatic validation",
                "Print-ready engineering reports",
            ],
        },
        Project {
            slug: "wattfinds",
            title: "WattFinds (DealBot)",
            tagline: "Autonomous deal aggregator with Rust web frontend",
            description: "Full-stack deal discovery platform: a Python scraper harvests Amazon products and promo campaigns, while a Rust/Axum website serves a fast, searchable deal feed. Automatic coupon matching, campaign expiry, Twitter posting pipeline, and SQLite/WAL storage.",
            stack: vec!["Rust", "Axum", "Askama", "Python", "SQLite"],
            categories: vec!["Software"],
            status: "Live",
            link: Some("https://wattfinds.com"),
            year: "2025-2026",
            highlights: vec![
                "Rust/Axum server with Askama compile-time templates",
                "Python scraper + automated social posting",
                "Campaign auto-matching by ASIN with expiry",
                "SQLite WAL mode with 60s busy-timeout",
            ],
        },
        Project {
            slug: "bollinger-ea",
            title: "BollingerReversion EA",
            tagline: "Validated quantitative trading strategy for MT5",
            description: "An Expert Advisor for MetaTrader 5 trading H4 Bollinger Band squeeze breakouts filtered by the 200 EMA trend. Backtested on all FX majors with in-sample and out-of-sample validation. 5:1 reward-risk with ATR-based stops.",
            stack: vec!["MQL5", "Python", "MT5 Strategy Tester"],
            categories: vec!["Software", "Quant"],
            status: "Validated",
            link: None,
            year: "2026",
            highlights: vec![
                "EURUSD IS 2018-2024: +155.3% over 544 trades",
                "OOS 2025-Feb 2026: +24.2% with no win-rate decay",
                "5:1 R:R with ATR(0.6) stop and ATR(3.0) target",
                "All FX majors tested independently, results reproducible",
            ],
        },
        Project {
            slug: "revit-advisor",
            title: "Revit Advisor",
            tagline: "AI assistant for Revit MEP workflows",
            description: "A pyRevit extension and Python backend that answers MEP engineering questions inside Autodesk Revit. Integrates an LLM with project context, a SQLite knowledge base, and structured prompts tuned for building services.",
            stack: vec!["Python", "pyRevit", "SQLite", "LLM APIs"],
            categories: vec!["Engineering", "Software", "AI"],
            status: "Active",
            link: None,
            year: "2025",
            highlights: vec![
                "Native Revit extension via pyRevit",
                "Context-aware prompts for MEP design",
                "Local SQLite knowledge base",
            ],
        },
        Project {
            slug: "jse-tracker",
            title: "JSE Tracker",
            tagline: "Jamaica Stock Exchange live data dashboard",
            description: "A full-stack tracker for the Jamaica Stock Exchange with a data-ingestion backend and a responsive frontend dashboard. Tracks price movements, volume, and historical performance across listed equities.",
            stack: vec!["Python", "JavaScript", "REST API"],
            categories: vec!["Software"],
            status: "Active",
            link: None,
            year: "2025",
            highlights: vec![
                "Real-time JSE equity data",
                "Historical trend visualisation",
                "Responsive dashboard frontend",
            ],
        },
        Project {
            slug: "solar-design",
            title: "Solar PV System Designs",
            tagline: "Grid-tie and hybrid solar installations across Jamaica",
            description: "Production solar PV system designs completed at HTG Engineering. Sizing, string layout, inverter selection, and compliance with JPS interconnection standards. Delivered using PVsyst for yield modelling and AutoCAD MEP for construction drawings.",
            stack: vec!["PVsyst", "AutoCAD MEP", "Revit"],
            categories: vec!["Engineering"],
            status: "Delivered",
            link: None,
            year: "2023-2025",
            highlights: vec![
                "String sizing and inverter selection",
                "Yield simulation with PVsyst",
                "JPS interconnection compliance",
            ],
        },
        Project {
            slug: "electrical-design",
            title: "Commercial & Residential Electrical Design",
            tagline: "Power, lighting, and ELV systems for live projects",
            description: "End-to-end electrical design for commercial and residential buildings. Power distribution, lighting layouts (photometric via Dialux Evo), ELV systems, and pole-line distribution. 3D lighting renders via Enscape and TwinMotion for client presentations.",
            stack: vec!["AutoCAD MEP", "Revit", "Dialux Evo", "Enscape"],
            categories: vec!["Engineering"],
            status: "Delivered",
            link: None,
            year: "2022-2025",
            highlights: vec![
                "Power distribution and panel schedules",
                "Photometric lighting design (Dialux Evo)",
                "3D walkthrough renders for client approval",
                "Pole-line distribution design",
            ],
        },
        Project {
            slug: "j1-tax-service",
            title: "J1TaxPro",
            tagline: "Tax refund service for J1/H2B visa workers",
            description: "A complete small-business package for J1 and H2B visa workers seeking US tax refunds. Includes a client tracker web app, tax prep quick-reference materials, service flyers, and an Instagram launch campaign with graphic assets.",
            stack: vec!["HTML/CSS/JS", "Instagram", "Business ops"],
            categories: vec!["Business", "Software"],
            status: "Launched",
            link: None,
            year: "2025",
            highlights: vec![
                "Client tracker single-page web app",
                "Tax prep quick-reference for J1/H2B workers",
                "Launch marketing kit (IG graphics, flyers)",
            ],
        },
        Project {
            slug: "mep-business",
            title: "Jamaica MEP Contractor Plan",
            tagline: "Full business plan for an MEP installation firm",
            description: "A complete go-to-market package for an MEP (mechanical, electrical, plumbing) drawing and installation contractor in Jamaica. Business plan, 90-day action tracker, proposal templates, onboarding pack, employee handbook, and equipment specs.",
            stack: vec!["Business strategy", "MEP engineering"],
            categories: vec!["Engineering", "Business"],
            status: "Ready",
            link: None,
            year: "2025",
            highlights: vec![
                "Jamaica-specific market strategy",
                "Proposal and onboarding templates",
                "Equipment specification library",
                "90-day execution tracker",
            ],
        },
        Project {
            slug: "lumiere",
            title: "Lumiere",
            tagline: "Multi-page web application with auth and billing",
            description: "A multi-page web application including landing, account, contact, and dashboard pages. Built from scratch with static HTML/CSS/JS and integrated account and payment flows.",
            stack: vec!["HTML/CSS/JS", "Stripe"],
            categories: vec!["Software"],
            status: "Active",
            link: None,
            year: "2025",
            highlights: vec![
                "Multi-page architecture",
                "Account and Stripe-powered billing",
                "Landing, contact, and dashboard pages",
            ],
        },
        Project {
            slug: "captcha-tester",
            title: "Captcha Tester",
            tagline: "Security research tool for captcha evaluation",
            description: "A testing harness for evaluating captcha implementations. Used for authorised security research and understanding captcha robustness across different vendors.",
            stack: vec!["Python", "Playwright"],
            categories: vec!["Software", "Security"],
            status: "Research",
            link: None,
            year: "2025",
            highlights: vec![
                "Captcha vendor comparison",
                "Automated test harness",
            ],
        },
        Project {
            slug: "subtitle-translator",
            title: "Subtitle Translator",
            tagline: "AI-powered subtitle translation tool",
            description: "A browser-based subtitle translation tool that parses SRT/VTT files and translates them using LLM APIs while preserving timing and formatting.",
            stack: vec!["JavaScript", "LLM APIs"],
            categories: vec!["Software", "AI"],
            status: "Live",
            link: None,
            year: "2025",
            highlights: vec![
                "Preserves subtitle timing",
                "Supports SRT and VTT formats",
                "Client-side processing",
            ],
        },
        Project {
            slug: "poker-assistant",
            title: "Poker Assistant",
            tagline: "Hand-analysis and strategy helper",
            description: "A Python web application that analyses poker hands, tracks sessions, and surfaces strategy suggestions. Flask-based with a templated frontend and a local data store.",
            stack: vec!["Python", "Flask", "HTML/CSS"],
            categories: vec!["Software"],
            status: "Active",
            link: None,
            year: "2025",
            highlights: vec![
                "Hand analysis engine",
                "Session tracking",
                "Strategy recommendations",
            ],
        },
        Project {
            slug: "neon-coil",
            title: "Neon Coil",
            tagline: "Mobile game project",
            description: "A mobile game in development with accompanying spec documents, dev roadmap, and agent-assisted workflow.",
            stack: vec!["Game dev", "Spec-driven development"],
            categories: vec!["Software", "Games"],
            status: "In progress",
            link: None,
            year: "2026",
            highlights: vec![
                "Spec-first development",
                "Mobile-native target",
            ],
        },
    ]
}
